config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("admin/", admin.site.urls),
]

# For development cases
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

lists/urls.py
from django.urls import path
from . import views

app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models


class AbstractItem(core_models.TimeStampedModel):
    """ Abstract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):
    """ RoomType Model Definition"""

    class Meta:
        verbose_name = "Room Type"
        ordering = ["name"]


class Amenity(AbstractItem):
    """ Amenity Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):
    """ Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):
    """ HouseRule Model Definition"""

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):
    """ Photo Model Definition """

    caption = models.CharField(max_length=80, blank=True)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


# Create your models here.
class Room(core_models.TimeStampedModel):
    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rule = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("rooms:detail", kwargs={"pk": self.pk})

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if all_reviews:
            for review in all_reviews:
                all_ratings += review.rating_average()

            return round(all_ratings / len(all_reviews), 2)
        elif not all_reviews:
            return 0

    def first_photo(self):
        (photo,) = self.photos.all()[:1]
        return photo.file.url

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="US").formfield()
    room_type = forms.ModelChoiceField(
        queryset=models.RoomType.objects.all(),
        empty_label="Any Kind",
        required=False,
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )

rooms/views.py
from django.views.generic import ListView, DetailView, View
from django.shortcuts import render
from django.core.paginator import Paginator
from django_countries import countries
from . import models, forms


# Create your views here.
class HomeView(ListView):
    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    parginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


class RoomDetail(DetailView):
    """ RoomDetail Definition """

    model = models.Room


class SearchView(View):
    def get(self, request):
        country = request.GET.get("country")

        if country:
            form = forms.SearchForm(request.GET)

            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                # * Connecting via Foreign Key
                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price

                if guests is not None:
                    filter_args["guests__gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                # * Connecting via Foreign Key
                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                # qs = models.Room.objects.filter(**filter_args).order_by("-created")
                # paginator = Paginator(qs, 10, orphans=5)
                # page = request.GET.get("page", 1)
                # rooms = paginator.get_page(page)

                rooms = models.Room.objects.filter(**filter_args).order_by("-created")

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )
        else:
            form = forms.SearchForm()

        return render(request, "rooms/search.html", {"form": form})

templates/rooms/detail.html
{% extends "base.html" %} 

{% block page_name %} 
    ROOM DETAIL 
{% endblock page_name %}

{%block content %} 

    <div>
        <h1>{{room.name}}</h1>
        <h3>{{room.description}}</h3>
    </div>
    <div>
        <h2>By: {{room.host.username}}
            {% if room.host.superhost %}
                (superhost)
            {% endif %}
        </h2>
        <h3>Amenities</h3>
        <ul>
            {% for a in room.amenities.all %}
                <li>{{a}}</li>
            {% endfor %}
        </ul>
        <h3>Facilities</h3>
        <ul>
            {% for f in room.facilities.all %}
                <li>{{f}}</li>
            {% endfor %}
        </ul>
        <h3>House Rules</h3>
        <ul>
            {% for r in room.house_rule.all %}
                <li>{{r}}</li>
            {% endfor %}
        </ul>
    </div>

   

{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %} 
{% load on_favs %}

{% block page_title %} 
    {{room.name}}
{% endblock page_title %}

{%block content %} 

    <div>
        <h1>{{room.name}}</h1>
        <h3>{{room.description}}</h3>
    </div>
    <div>
        <h2>By: 
            <a href="{{room.host.get_absolute_url}}">{{room.host.username}}</a>
            {% if room.host.superhost %}
                (superhost)
            {% endif %}
        </h2>
        <h3>Amenities</h3>
        <ul>
            {% for a in room.amenities.all %}
                <li>{{a}}</li>
            {% endfor %}
        </ul>
        <h3>Facilities</h3>
        <ul>
            {% for f in room.facilities.all %}
                <li>{{f}}</li>
            {% endfor %}
        </ul>
        <h3>House Rules</h3>
        <ul>
            {% for r in room.house_rule.all %}
                <li>{{r}}</li>
            {% endfor %}
        </ul>
    </div>
    <div>   
        {% if user.is_authenticated %}
            {% on_favs room as on_favs_boolean %}
            {% if on_favs_boolean %}
                <a href="{% url "lists:toggle-room" room.pk %}?action=remove">Remove from Favorites</a>
            {% else %}
                <a href="{% url "lists:toggle-room" room.pk %}?action=add">Save to Favorites</a>
            {% endif %}
        {% endif %}       
    </div>

   

{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}

{% block page_title %}
    HOME
{% endblock page_title %}

{% block content %}
    <div class="container mx-auto pb-10">
        <div class="rounded-xl bg-gray-800 -mx-40 h-50vh mt-32 mb-24 bg-cover bg-center" style="background-image:url(https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop)"></div>
        <div class="flex flex-wrap -mx-40 mb-10">
            {% for room in rooms %}
                {% include 'mixins/room_card.html' with room=room %}
            {% endfor %}
        </div>
        <div class="flex items-center justify-center mx-auto container">
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}" class="text-teal-500">
                    <i class="fas fa-arrow-left fa-lg"></i>
                </a>
            {% endif %}

            <span class="mx-3 font-medium text-lg">
                {{page_obj.number}} of {{page_obj.paginator.num_pages}}
            </span>
            
            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}" class="text-teal-500">
                    <i class="fas fa-arrow-right fa-lg"></i>
                </a>
            {% endif %}
        </div>
    </div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}


{% block page_title %}
    Search
{% endblock page_title %}


{% block search-bar %}
{% endblock search-bar %}


{% block content %}
    
    <h2>Search!</h2>

    <form method="GET" action="{% url 'rooms:search' %}">
        {{form.as_p}}
        <button>Search</button>
    </form>

    <h3>Results</h3>
        {% for room in rooms %}
            <h4>{{room.name}}</h4>
        {% endfor %}

        
{% endblock content %}
    
    