config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("users/", include("users.urls", namespace="users")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("admin/", admin.site.urls),
]

# For development cases
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <title>{% block page_title %}{% endblock page_title %} | QBnb</title>
</head>

<body class="text-gray-800 mt-24 font-light">
  {% include "partials/messages.html" %}
  <header class="container max-w-full inset-0 flex items-center justify-between px-6 h-20 border-b border-gray-400 fixed bg-white">
    <div class="flex items-center w-1/3">
      <a class="mr-6" href="{% url "core:home" %}">
        <img class="w-6" src="{% static 'img/logo.png' %}" />
      </a>
      {% block search-bar %}
        <form class="w-9/12" method="GET" action="{% url 'rooms:search' %}">
          <input class="search-box border font-medium placeholder-gray-600 px-5 py-3 rounded-sm w-full shadow-md hover:shadow-lg focus:outline-none" name="city" type="text" placeholder="Search by City"/>
        </form> 
      {% endblock search-bar %}
    </div>
    {% include "partials/nav.html" %}
  </header>
  {% block content %} {% endblock content%}
  {% include "partials/footer.html" %}
</body>

</html>